# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestHotel1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testHotel1(self):
    self.driver.get("http://127.0.0.1:5500/app/index.html")
    self.driver.set_window_size(733, 696)
    self.driver.find_element(By.ID, "checkin").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1)").click()
    self.driver.find_element(By.ID, "checkin").click()
    self.driver.find_element(By.ID, "checkin").click()
    self.driver.find_element(By.ID, "checkin").send_keys("2026-05-25")
    self.driver.find_element(By.ID, "checkout").click()
    self.driver.find_element(By.ID, "checkout").send_keys("2026-06-10")
    dropdown = self.driver.find_element(By.ID, "hospedes")
    dropdown.find_element(By.XPATH, "//option[. = '2 hóspedes']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    self.driver.find_element(By.ID, "btn-pesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".room-card:nth-child(1) .btn").click()
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("luna@gmail.com")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "formReserva").click()
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("Luna")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("luna@gmail.com")
    self.driver.find_element(By.ID, "telefone").click()
    self.driver.find_element(By.ID, "telefone").send_keys("123456789")
    self.driver.find_element(By.ID, "btnConfirmar").click()
    self.driver.find_element(By.LINK_TEXT, "Voltar para Home").click()
    self.driver.find_element(By.LINK_TEXT, "Quartos").click()
    self.driver.find_element(By.LINK_TEXT, "Minhas Reservas").click()
    self.driver.find_element(By.LINK_TEXT, "Cancelar Reserva").click()
    self.driver.find_element(By.CSS_SELECTOR, ".info-box:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".info-box:nth-child(5)").click()
    self.driver.find_element(By.LINK_TEXT, "Cancelar Reserva").click()
    self.driver.find_element(By.ID, "codigo").click()
    self.driver.find_element(By.ID, "codigo").send_keys("HTL-68116")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("luna@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Quartos").click()
    self.driver.find_element(By.LINK_TEXT, "Minhas Reservas").click()
  
